### PR TITLE
Update requirements to support django 4.2

### PR DESCRIPTION
**Pull request by TimothyLoyer**
- Bump package version (mirroring minimum Django version)
- Fix package repo URL
- Update minimum Python version to 3.11
- Pin Django version to 4.2.x

### CODE REVIEW

**Review by noelleleigh — COMMENTED** [review]
Here's what my environment installed when I ran `pip install .`:

```
Successfully installed 
asgiref-3.7.2 
django-5.0.1 
django-middleware-4.2 
sqlparse-0.4.4
```

Have you tested this code with Django 5.0?

**Comment by TimothyLoyer** [comment]
> Here's what my environment installed when I ran `pip install .`:
> 
> ```
> Successfully installed 
> asgiref-3.7.2 
> django-5.0.1 
> django-middleware-4.2 
> sqlparse-0.4.4
> ```
> 
> Have you tested this code with Django 5.0?

No - do you think I should pin 4.2.* until we need it?

**Comment by noelleleigh** [comment]
> > Have you tested this code with Django 5.0?
> 
> No - do you think I should pin 4.2.* until we need it? I did run django-codemod against it though, and it didn't see any deprecations for 4.x.

Yeah, I think sticking with 4.2 explicitly would be a good idea.

**Comment by TimothyLoyer** [comment]
> > Here's what my environment installed when I ran `pip install .`:
> > ```
> > Successfully installed 
> > asgiref-3.7.2 
> > django-5.0.1 
> > django-middleware-4.2 
> > sqlparse-0.4.4
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Have you tested this code with Django 5.0?
> 
> No - do you think I should pin 4.2.* until we need it?



> > > Have you tested this code with Django 5.0?
> > 
> > 
> > No - do you think I should pin 4.2.* until we need it? I did run django-codemod against it though, and it didn't see any deprecations for 4.x.
> 
> Yeah, I think sticking with 4.2 explicitly would be a good idea.

Done

**Review by noelleleigh — APPROVED** [review]

**Pull request merged**
